server:
  port: 8080

logging:
  file: logfile.log
  level:
    net.mert.reportingapi: DEBUG
    org: ERROR
    com: ERROR

reportingapi:
  url: "https://sandbox-reporting.rpdpymnt.com/api/v3"

management:
  endpoints:
    web:
      exposure:
        include: logfile, health
